//! The type-erased data-access surface behind generated CRUD.
//!
//! `#[model]` emits one hidden [`ModelResource`] implementation per struct,
//! containing *typed* ORM calls — the checked `insert!`/`update!` macros and
//! the `Col`-token dynamic builder, monomorphized for that table at compile
//! time. The trait erases the row type (rows cross as JSON) so the framework's
//! generic handlers can drive any model through one object-safe interface.
//! Nothing here assembles SQL from strings.

use fse_orm::Cond;
use futures::future::BoxFuture;
use std::collections::HashMap;

/// The database handle generated resource code runs against.
pub type Db = sqlx::SqlitePool;

/// A database-level result (`sqlx::Result` under a framework-stable name so
/// emitted code doesn't need a direct `sqlx` path).
pub type DbResult<T> = sqlx::Result<T>;

/// Submitted form fields, as the urlencoded body parses: one value per name.
pub type FormData = HashMap<String, String>;

/// Parameters of a generated list page. All fields come from query-string
/// input and are validated inside the generated code: unknown sort/filter
/// column names are ignored, `page`/`per_page` are clamped.
#[derive(Debug, Clone, Default)]
pub struct ListQuery {
    pub search: Option<String>,
    /// `(column, value)` pairs; only `#[ui(filter)]` columns match.
    pub filters: Vec<(String, String)>,
    /// Column to sort by; must name a real column or the default order is
    /// used (`created_at DESC` when present, else primary key DESC).
    pub sort: Option<String>,
    pub desc: bool,
    pub page: i64,
    pub per_page: i64,
}

/// One page of type-erased rows plus the total count over the same filter.
#[derive(Debug, Clone)]
pub struct ListResult {
    pub rows: Vec<serde_json::Value>,
    pub total: i64,
    pub page: i64,
    pub per_page: i64,
}

impl ListResult {
    #[must_use]
    pub fn total_pages(&self) -> i64 {
        if self.per_page <= 0 {
            return 0;
        }
        (self.total + self.per_page - 1) / self.per_page
    }
}

/// One rejected form field: which field and a stable machine-readable code
/// (`required`, `invalid_number`, `invalid_option`, `invalid_value`,
/// `invalid_datetime`, `not_unique`) — the generic templates translate codes
/// through the locale files.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize)]
pub struct FieldError {
    pub field: &'static str,
    pub code: &'static str,
}

pub type FormErrors = Vec<FieldError>;

/// Typed data access for one registered model, generated by `#[model]`.
///
/// The nested results separate concerns: the outer [`DbResult`] is an
/// infrastructure failure, the inner `Result<_, FormErrors>` is user input
/// the generated form should re-render with error messages.
pub trait ModelResource: Send + Sync {
    fn list<'a>(&'a self, db: &'a Db, q: &'a ListQuery) -> BoxFuture<'a, DbResult<ListResult>>;

    fn get<'a>(&'a self, db: &'a Db, id: i64) -> BoxFuture<'a, DbResult<Option<serde_json::Value>>>;

    /// Look a row up by the `public_read` column. Always `None` for models
    /// without `public_read`.
    fn get_by_public<'a>(
        &'a self,
        db: &'a Db,
        key: &'a str,
    ) -> BoxFuture<'a, DbResult<Option<serde_json::Value>>>;

    /// Validate + insert; `Ok(Ok(id))` is the new row's primary key.
    fn create<'a>(
        &'a self,
        db: &'a Db,
        form: &'a FormData,
    ) -> BoxFuture<'a, DbResult<Result<i64, FormErrors>>>;

    fn update<'a>(
        &'a self,
        db: &'a Db,
        id: i64,
        form: &'a FormData,
    ) -> BoxFuture<'a, DbResult<Result<(), FormErrors>>>;

    /// Returns the number of deleted rows (0 = was already gone).
    fn delete<'a>(&'a self, db: &'a Db, id: i64) -> BoxFuture<'a, DbResult<u64>>;
}

/// AND a condition onto an optional accumulator — the shape the generated
/// list code composes search + filters with.
#[must_use]
pub fn and_opt(acc: Option<Cond>, cond: Cond) -> Option<Cond> {
    Some(match acc {
        Some(prev) => prev.and(cond),
        None => cond,
    })
}
