//! The type-erased data-access surface behind generated CRUD.
//!
//! `#[model]` emits one hidden [`ModelResource`] implementation per struct,
//! containing *typed* ORM calls — the checked `insert!`/`update!` macros and
//! the `Col`-token dynamic builder, monomorphized for that table at compile
//! time. The trait erases the row type (rows cross as JSON) so the framework's
//! generic handlers can drive any model through one object-safe interface.
//! Nothing here assembles SQL from strings.

use fse_orm::Cond;
use futures::future::BoxFuture;
use std::collections::HashMap;

use super::hooks::{Access, CurrentUser, Ref, RowView};
use crate::error::AppResult;

/// The database handle generated resource code runs against.
pub type Db = sqlx::SqlitePool;

/// A database-level result (`sqlx::Result` under a framework-stable name so
/// emitted code doesn't need a direct `sqlx` path).
pub type DbResult<T> = sqlx::Result<T>;

/// Submitted form fields, as the urlencoded body parses: one value per name.
pub type FormData = HashMap<String, String>;

/// Parameters of a generated list page. All fields come from query-string
/// input and are validated inside the generated code: unknown sort/filter
/// column names are ignored, `page`/`per_page` are clamped.
#[derive(Debug, Clone, Default)]
pub struct ListQuery {
    pub search: Option<String>,
    /// `(param, value)` pairs from `#[ui(filter)]` columns: the column name
    /// for exact/contains filters, `{col}_from` / `{col}_to` for ranges.
    pub filters: Vec<(String, String)>,
    /// Column to sort by; must name a real column or the default order is
    /// used (`created_at DESC` when present, else primary key DESC).
    pub sort: Option<String>,
    pub desc: bool,
    pub page: i64,
    pub per_page: i64,
}

/// One page of type-erased rows plus the total count over the same filter.
#[derive(Debug, Clone)]
pub struct ListResult {
    pub rows: Vec<serde_json::Value>,
    pub total: i64,
    pub page: i64,
    pub per_page: i64,
}

impl ListResult {
    #[must_use]
    pub fn total_pages(&self) -> i64 {
        if self.per_page <= 0 {
            return 0;
        }
        (self.total + self.per_page - 1) / self.per_page
    }
}

/// One rejected form field: which field and a stable machine-readable code
/// (`required`, `invalid_number`, `invalid_option`, `invalid_value`,
/// `invalid_datetime`, `not_unique`) — the generic templates translate codes
/// through the locale files.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize)]
pub struct FieldError {
    pub field: &'static str,
    pub code: &'static str,
}

pub type FormErrors = Vec<FieldError>;

/// Typed data access for one registered model, generated by `#[model]`.
///
/// Every read and write runs the model's access rules — the `owner` column,
/// [`ModelHooks`](super::ModelHooks) and a nested model's parent filter, all
/// carried by the [`Access`] — so the handlers stay generic. A row outside
/// the requester's scope is `AppError::NotFound`; a write without a user or
/// refused by a hook is `AppError::NoAuth`. The inner
/// `Result<_, FormErrors>` is user input the form should re-render with
/// error messages.
pub trait ModelResource: Send + Sync {
    fn list<'a>(
        &'a self,
        db: &'a Db,
        access: Access<'a>,
        q: &'a ListQuery,
    ) -> BoxFuture<'a, AppResult<ListResult>>;

    /// One row by primary key, with the requester's rights on it.
    fn get<'a>(
        &'a self,
        db: &'a Db,
        access: Access<'a>,
        id: i64,
    ) -> BoxFuture<'a, AppResult<Option<RowView>>>;

    /// Look a row up by the `public_read` column (public scope applies).
    /// Always `None` for models without `public_read`.
    fn get_by_public<'a>(
        &'a self,
        db: &'a Db,
        key: &'a str,
    ) -> BoxFuture<'a, AppResult<Option<serde_json::Value>>>;

    /// Ids of every row `access` may see, or `None` when its scope doesn't
    /// restrict at all. Nested models use it to inherit their parent's
    /// visibility.
    fn visible_ids<'a>(
        &'a self,
        db: &'a Db,
        access: Access<'a>,
    ) -> BoxFuture<'a, AppResult<Option<Vec<i64>>>>;

    /// Title and relation keys of the rows `ids`, for showing them inside
    /// rows that point at them. Unscoped by design: it only ever reveals the
    /// title of a row another visible row already links to.
    fn refs<'a>(
        &'a self,
        db: &'a Db,
        ids: &'a [i64],
    ) -> BoxFuture<'a, AppResult<HashMap<i64, Ref>>>;

    /// [`ModelHooks::can_create`](super::ModelHooks::can_create) for the
    /// access's user and parent (`false` without a user).
    fn can_create<'a>(&'a self, db: &'a Db, access: Access<'a>) -> BoxFuture<'a, AppResult<bool>>;

    /// Validate + insert; `Ok(Ok(id))` is the new row's primary key.
    fn create<'a>(
        &'a self,
        db: &'a Db,
        access: Access<'a>,
        form: &'a FormData,
    ) -> BoxFuture<'a, AppResult<Result<i64, FormErrors>>>;

    fn update<'a>(
        &'a self,
        db: &'a Db,
        access: Access<'a>,
        id: i64,
        form: &'a FormData,
    ) -> BoxFuture<'a, AppResult<Result<(), FormErrors>>>;

    fn delete<'a>(
        &'a self,
        db: &'a Db,
        access: Access<'a>,
        id: i64,
    ) -> BoxFuture<'a, AppResult<()>>;

    /// Run the row action `action` (`#[model(actions(...))]`) on row `id`.
    /// Unknown actions and rows outside the scope are `NotFound`; a refused
    /// [`can_act`](super::ModelHooks::can_act) is `NoAuth`.
    fn act<'a>(
        &'a self,
        db: &'a Db,
        access: Access<'a>,
        id: i64,
        action: &'a str,
        form: &'a FormData,
    ) -> BoxFuture<'a, AppResult<()>>;
}

/// Typed data access for one many-to-many join table
/// (`#[model(link = owner_col)]`), generated by `#[model]`. Adding and
/// removing a link is inserting and deleting the join row, so the join
/// struct's own [`ModelHooks`](super::ModelHooks) apply: `can_create` (with
/// the owner id as `parent_id`), `after_save`, `can_delete`,
/// `before_delete`/`after_delete`.
pub trait LinkResource: Send + Sync {
    /// Ids of the rows linked to `owner_id`.
    fn linked<'a>(&'a self, db: &'a Db, owner_id: i64) -> BoxFuture<'a, AppResult<Vec<i64>>>;

    /// Link `other_id` to `owner_id`; `Ok(false)` when it already was.
    fn add<'a>(
        &'a self,
        db: &'a Db,
        user: &'a CurrentUser,
        owner_id: i64,
        other_id: i64,
    ) -> BoxFuture<'a, AppResult<bool>>;

    /// Unlink; `Ok(false)` when it wasn't linked.
    fn remove<'a>(
        &'a self,
        db: &'a Db,
        user: &'a CurrentUser,
        owner_id: i64,
        other_id: i64,
    ) -> BoxFuture<'a, AppResult<bool>>;
}

/// AND a condition onto an optional accumulator — the shape the generated
/// list code composes search + filters with.
#[must_use]
pub fn and_opt(acc: Option<Cond>, cond: Cond) -> Option<Cond> {
    Some(match acc {
        Some(prev) => prev.and(cond),
        None => cond,
    })
}
