//! One `#[model]` struct per file — **these structs are the app.** Each one
//! defines its table (migrations generated by `fse migrate`), its typed ORM
//! queries, and its generated admin CRUD endpoints + pages. `#[ui(...)]`
//! attributes shape the generated UI; everything is overridable per route
//! (`services/`) or per page (`src/frontend/src/pages/`).

pub mod order;
pub mod product;
pub mod user;
