pub use crate::{
    AppData, Env, FrameworkApp, RenderError, RenderTplExt,
    auth::{AuthUser, create_jwt, hash_password, read_jwt, verify_password},
    config::{Config, SmtpConfig},
    error::{AppError, AppResult, ErrorContext, ResultExt},
    i18n::{inject_locale_context, load_locale},
    mail::send_mail,
    rate_limiter::{auth_rate_limiter, custom_rate_limiter, general_rate_limiter},
    structs::{DefaultRole, Role, User},
    themes::{Theme, ThemeManifest},
    uploads::{UploadError, save_upload},
};

// Struct-defined apps: `#[model(...)]` on a struct expands to
// `#[derive(Table, Debug, Clone)]` plus a registration in the runtime model
// registry (`full_stack_engine::models`) — the framework generates admin
// CRUD endpoints and pages from that metadata, configured by the macro's
// arguments and field-level `#[ui(...)]` attributes, all validated at
// compile time.
pub use full_stack_engine_macros::model;

// The fse ORM: `#[derive(Table)]` structs in `src/tables/` define the schema
// (migrations are generated by `fse migrate`), the query macros expand to
// compile-time-checked sqlx, and `Table::find()` is the dynamic escape
// hatch. `delete!` is re-exported as `delete_rows!` because actix-web's
// `#[delete]` route attribute below already owns the name.
pub use fse_orm::{
    self, Col, DbEnum, Page, Table, count, delete as delete_rows, find, find_one, find_page,
    insert, update,
};

pub use actix_web::{
    self, HttpResponse, Responder, cookie, delete, get, http, http::header::LOCATION, main, post,
    put, web, web::Data, web::Form,
};
// actix-multipart is deliberately not re-exported: `#[derive(MultipartForm)]`
// hardcodes a bare `actix_multipart` crate-root reference in its generated
// code (verified — removing the app's own dependency breaks the derive with
// "cannot find `actix_multipart` in the crate root"), so an app using it
// needs its own direct dependency regardless.
pub use actix_files;
pub use chrono;
pub use include_dir;
// Observability. The `debug!`/`info!`/`warn!`/`error!` names now resolve to
// `tracing`'s macros rather than `log`'s: the call syntax is identical, so
// existing handlers keep compiling, but each event is attached to the span of
// the request it happened in and can carry structured fields:
//
//     info!(order.id = id, "order placed");
//
// `#[instrument]` puts a handler's own span on the trace, and `RequestId` is
// the correlation id echoed in the `x-request-id` response header.
//
// `log` stays re-exported so `log::info!` paths in existing app code keep
// working — those records are bridged into the same subscriber.
pub use log;
pub use reqwest;
pub use serde::{self, Deserialize, Serialize};
pub use serde_json::{self, json};
pub use tera::{self, Context};
pub use tokio_cron_scheduler;
pub use tracing::{self, debug, error, info, instrument, trace, warn};
pub use tracing_actix_web::{RequestId, RootSpan};
// Secrets are `SecretString` (see `config`); `ExposeSecret` is what makes
// reading one an explicit, reviewable call.
pub use secrecy::{ExposeSecret, SecretString};
// Declarative request validation: `#[derive(Validate)]` on a form struct plus
// `form.validate()?` in the handler, instead of hand-rolled length and
// `contains('@')` checks.
pub use uuid;
pub use validator::{self, Validate, ValidationError, ValidationErrors};

pub use std::convert::{TryFrom, TryInto};
