//! Typed column tokens and conditions for the dynamic query builder — the
//! unchecked (sqlx-without-`!`) escape hatch for queries whose shape is only
//! known at runtime. Column tokens are generated by `derive(Table)` from the
//! same structs that generate the migrations, so names can never be stale;
//! what is *not* verified here is the statement against the live schema.

use std::marker::PhantomData;

use sqlx::{QueryBuilder, Sqlite};

/// A value that can be bound into a dynamic query.
pub trait Bindable:
    Clone + Send + Sync + 'static + for<'q> sqlx::Encode<'q, Sqlite> + sqlx::Type<Sqlite>
{
}
impl<T> Bindable for T where
    T: Clone + Send + Sync + 'static + for<'q> sqlx::Encode<'q, Sqlite> + sqlx::Type<Sqlite>
{
}

pub(crate) type BindFn = Box<dyn for<'q> Fn(&mut QueryBuilder<'q, Sqlite>) + Send + Sync>;

pub(crate) fn bind_fn<V: Bindable>(value: V) -> BindFn {
    Box::new(move |qb| {
        qb.push_bind(value.clone());
    })
}

/// A typed column token, e.g. `Product::STATUS: Col<ProductStatus>`.
/// Generated by `derive(Table)`; `T` is the field type with `Option`
/// stripped, so binds stay Rust-type-checked.
pub struct Col<T> {
    name: &'static str,
    _marker: PhantomData<fn() -> T>,
}

impl<T> Clone for Col<T> {
    fn clone(&self) -> Self {
        *self
    }
}
impl<T> Copy for Col<T> {}

impl<T> Col<T> {
    pub const fn new(name: &'static str) -> Self {
        Self { name, _marker: PhantomData }
    }

    pub const fn name(self) -> &'static str {
        self.name
    }

    pub fn asc(self) -> Order {
        Order(format!("{} ASC", self.name))
    }

    pub fn desc(self) -> Order {
        Order(format!("{} DESC", self.name))
    }

    pub fn is_null(self) -> Cond {
        Cond::fragment(format!("{} IS NULL", self.name))
    }

    pub fn is_not_null(self) -> Cond {
        Cond::fragment(format!("{} IS NOT NULL", self.name))
    }
}

impl<T: Bindable> Col<T> {
    fn compare(self, op: &str, value: impl Into<T>) -> Cond {
        Cond {
            fragments: vec![format!("{} {op} ", self.name), String::new()],
            binds: vec![bind_fn(value.into())],
        }
    }

    pub fn eq(self, value: impl Into<T>) -> Cond {
        self.compare("=", value)
    }
    pub fn ne(self, value: impl Into<T>) -> Cond {
        self.compare("<>", value)
    }
    pub fn lt(self, value: impl Into<T>) -> Cond {
        self.compare("<", value)
    }
    pub fn lte(self, value: impl Into<T>) -> Cond {
        self.compare("<=", value)
    }
    pub fn gt(self, value: impl Into<T>) -> Cond {
        self.compare(">", value)
    }
    pub fn gte(self, value: impl Into<T>) -> Cond {
        self.compare(">=", value)
    }

    /// `col IN (...)` with one placeholder per value — the thing the checked
    /// macros can't do, because the placeholder count is a runtime fact.
    /// An empty list matches nothing.
    pub fn in_(self, values: impl IntoIterator<Item = T>) -> Cond {
        let values: Vec<T> = values.into_iter().collect();
        if values.is_empty() {
            return Cond::fragment("0 = 1".into());
        }
        let mut fragments = vec![format!("{} IN (", self.name)];
        fragments.extend(std::iter::repeat_n(", ".to_string(), values.len() - 1));
        fragments.push(")".into());
        Cond { fragments, binds: values.into_iter().map(bind_fn).collect() }
    }
}

impl Col<String> {
    pub fn contains(self, value: impl Into<String>) -> Cond {
        Cond {
            fragments: vec![format!("{} LIKE '%' || ", self.name), " || '%'".into()],
            binds: vec![bind_fn(value.into())],
        }
    }

    pub fn starts_with(self, value: impl Into<String>) -> Cond {
        Cond {
            fragments: vec![format!("{} LIKE ", self.name), " || '%'".into()],
            binds: vec![bind_fn(value.into())],
        }
    }
}

/// An ORDER BY item, from [`Col::asc`]/[`Col::desc`].
pub struct Order(pub(crate) String);

/// One WHERE condition: SQL fragments interleaved with binds
/// (`fragments.len() == binds.len() + 1` conceptually; trailing fragments
/// may be empty). Combine with [`Cond::and`]/[`Cond::or`]; the builders'
/// `filter` calls AND their conditions.
pub struct Cond {
    pub(crate) fragments: Vec<String>,
    pub(crate) binds: Vec<BindFn>,
}

impl Cond {
    fn fragment(sql: String) -> Self {
        Self { fragments: vec![sql], binds: Vec::new() }
    }

    pub fn and(self, other: Cond) -> Cond {
        combine(self, " AND ", other)
    }

    pub fn or(self, other: Cond) -> Cond {
        combine(self, " OR ", other)
    }

    pub(crate) fn apply(&self, qb: &mut QueryBuilder<'_, Sqlite>) {
        for (i, fragment) in self.fragments.iter().enumerate() {
            qb.push(fragment.as_str());
            if let Some(bind) = self.binds.get(i) {
                bind(qb);
            }
        }
    }
}

fn combine(a: Cond, separator: &str, b: Cond) -> Cond {
    let mut fragments = a.fragments;
    let mut binds = a.binds;

    // Merge: `(` + a + separator + b + `)`, gluing the boundary fragments so
    // fragments still interleave 1:1 with binds.
    let mut b_fragments = b.fragments.into_iter();
    let boundary = b_fragments.next().unwrap_or_default();
    if binds.len() == fragments.len() {
        // a ended on a bind with no trailing fragment.
        fragments.push(format!("{separator}{boundary}"));
    } else {
        let last = fragments.last_mut().expect("condition has fragments");
        last.push_str(separator);
        last.push_str(&boundary);
    }
    fragments.extend(b_fragments);
    binds.extend(b.binds);

    fragments.first_mut().expect("condition has fragments").insert(0, '(');
    if binds.len() == fragments.len() {
        fragments.push(")".into());
    } else {
        fragments.last_mut().expect("condition has fragments").push(')');
    }
    Cond { fragments, binds }
}
