//! Runtime support for the fse ORM. The interesting code is generated by
//! [`Table`]/[`DbEnum`] as compile-time-checked sqlx calls; this crate holds
//! the small amount of shared runtime the generated code leans on. The
//! dynamic (unchecked, sqlx-without-`!` style) query builder lands in
//! build-order step 4: `Col<T>`, `SelectBuilder`, `UpdateBuilder`.

pub use fse_orm_macros::{DbEnum, Table};

use serde::Serialize;
use serde::de::DeserializeOwned;

/// One page of a paginated list query plus the total row count over the same
/// filter — the result of `fetch_page`, covering the ubiquitous
/// "COUNT + SELECT LIMIT/OFFSET" pattern with a single query definition.
#[derive(Debug, Clone)]
pub struct Page<T> {
    pub rows: Vec<T>,
    pub total: i64,
}

/// Decode a `#[orm(json)]` column (stored as TEXT) back into its Rust type.
pub fn from_json_str<T: DeserializeOwned>(column: &'static str, raw: &str) -> sqlx::Result<T> {
    serde_json::from_str(raw).map_err(|e| sqlx::Error::ColumnDecode {
        index: column.into(),
        source: Box::new(e),
    })
}

pub fn opt_from_json_str<T: DeserializeOwned>(
    column: &'static str,
    raw: Option<&str>,
) -> sqlx::Result<Option<T>> {
    raw.map(|raw| from_json_str(column, raw)).transpose()
}

/// Encode a `#[orm(json)]` field for storage as TEXT.
pub fn to_json_string<T: Serialize>(value: &T) -> sqlx::Result<String> {
    serde_json::to_string(value).map_err(|e| sqlx::Error::Encode(Box::new(e)))
}

pub fn opt_to_json_string<T: Serialize>(value: Option<&T>) -> sqlx::Result<Option<String>> {
    value.map(to_json_string).transpose()
}
