//! Runtime support for the fse ORM. The interesting code is generated by
//! [`Table`]/[`DbEnum`] and the query macros as compile-time-checked sqlx
//! calls; this crate holds the small amount of shared runtime the generated
//! code leans on.

pub use fse_orm_macros::{DbEnum, Table, count, delete, find, find_one, find_page, update};

use serde::Serialize;
use serde::de::DeserializeOwned;

/// One page of a paginated list query plus the total row count over the same
/// filter — the result of `fetch_page`, covering the ubiquitous
/// "COUNT + SELECT LIMIT/OFFSET" pattern with a single query definition.
#[derive(Debug, Clone)]
pub struct Page<T> {
    pub rows: Vec<T>,
    pub total: i64,
}

/// Decode a `#[orm(json)]` column (stored as TEXT) back into its Rust type.
pub fn from_json_str<T: DeserializeOwned>(column: &'static str, raw: &str) -> sqlx::Result<T> {
    serde_json::from_str(raw).map_err(|e| sqlx::Error::ColumnDecode {
        index: column.into(),
        source: Box::new(e),
    })
}

pub fn opt_from_json_str<T: DeserializeOwned>(
    column: &'static str,
    raw: Option<&str>,
) -> sqlx::Result<Option<T>> {
    raw.map(|raw| from_json_str(column, raw)).transpose()
}

/// Decode a `DbEnum` column (stored as TEXT) via its `FromStr`.
pub fn parse_db_value<T>(column: &'static str, raw: &str) -> sqlx::Result<T>
where
    T: std::str::FromStr,
    T::Err: Into<Box<dyn std::error::Error + Send + Sync>>,
{
    raw.parse().map_err(|e: T::Err| sqlx::Error::ColumnDecode {
        index: column.into(),
        source: e.into(),
    })
}

pub fn opt_parse_db_value<T>(column: &'static str, raw: Option<&str>) -> sqlx::Result<Option<T>>
where
    T: std::str::FromStr,
    T::Err: Into<Box<dyn std::error::Error + Send + Sync>>,
{
    raw.map(|raw| parse_db_value(column, raw)).transpose()
}

/// Encode a `#[orm(json)]` field for storage as TEXT.
pub fn to_json_string<T: Serialize>(value: &T) -> sqlx::Result<String> {
    serde_json::to_string(value).map_err(|e| sqlx::Error::Encode(Box::new(e)))
}

pub fn opt_to_json_string<T: Serialize>(value: Option<&T>) -> sqlx::Result<Option<String>> {
    value.map(to_json_string).transpose()
}
